variables:
  COMPOSE_FILE: test.yaml
  COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  MQT_PATH: /tmp/maintainer-quality-tools
  MQT_REPO: https://github.com/OCA/maintainer-quality-tools.git
  REVIEW_DOMAIN: ci.gitlab.tecnativa.com
  REVIEW_PORT: 81

# Build
Pull and build images on private addons:
  stage: build
  script:
    - docker-compose down -v --remove-orphans
    - docker-compose build --pull
    - docker-compose pull

# Lint
Pylint for main branches on private addons:
  variables:
    CFG: travis_run_pylint.cfg
  script:
    - &pylint
      docker-compose run --rm --user root -e LOG_LEVEL=WARNING odoo bash -c "
        git clone --depth 1 $MQT_REPO $MQT_PATH &&
        pip install -q --no-cache pylint-odoo &&
        pylint --load-plugins pylint_odoo -d C8101
          --rcfile $MQT_PATH/travis/cfg/$CFG
          custom/src/private/*"
  only:
    - &main_branches ^\d+\.\d+$

Pylint for merge requests on private addons:
  variables:
    CFG: travis_run_pylint_pr.cfg
  script:
    - *pylint
  except:
    - *main_branches

Pylint beta on private addons:
  allow_failure: true
  variables:
    CFG: travis_run_pylint_beta.cfg
  script:
    - *pylint

Flake8 on private addons:
  script:
    - docker-compose run --rm --user root -e LOG_LEVEL=WARNING odoo bash -c "
        git clone --depth 1 $MQT_REPO $MQT_PATH &&
        pip install -q --no-cache flake8 &&
        cd custom/src/private &&
        $MQT_PATH/travis/test_flake8"

# Automated tests
Install and test private addons:
  script:
    - PRIVATE_ADDONS="$(ls -1 odoo/custom/src/private | tr -s '\n' ,)"
    - test -n "$PRIVATE_ADDONS" || echo No private addons found
    - test -z "$PRIVATE_ADDONS" ||
      docker-compose run --rm odoo --stop-after-init -i $PRIVATE_ADDONS
    - test -z "$PRIVATE_ADDONS" ||
      docker-compose run --rm odoo unittest $PRIVATE_ADDONS

# Runbot
Boot runbot:
  stage: deploy
  variables:
    DOMAIN_TEST: $CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
  environment:
    name: review $CI_COMMIT_REF_NAME
    # TODO Reuse $DOMAIN_TEST instead
    # HACK https://gitlab.com/gitlab-org/gitlab-runner/issues/2487
    url: http://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN:$REVIEW_PORT
    on_stop: Destroy runbot
  script:
    - docker-compose up -d

Destroy runbot:
  stage: deploy
  when: manual
  environment:
    name: review $CI_COMMIT_REF_NAME
    action: stop
  script:
    - docker-compose down -v --rmi local --remove-orphans
