variables:
  COMPOSE_FILE: test.yaml
  COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  REVIEW_DOMAIN: ci.gitlab.tecnativa.com
  REVIEW_PORT: 81

stages:
  - build
  - install
  - test
  - deploy

# Build
Pull and build images:
  stage: build
  script:
    - build

# Install
Install addons:
  stage: install
  variables:
    ADDON_CATEGORIES: "--private --extra"
  script:
    - addons-install

# Lint
Pylint loose:
  variables:
    LINT_MODE: "loose"
  script: &pylint
    - pylint
  only: &main_branches
    - ^\d+\.\d+$

Pylint strict: &pylint_strict
  variables:
    LINT_MODE: "strict"
  script: *pylint
  except: *main_branches

Pylint strict warnings:
  <<: *pylint_strict
  allow_failure: true
  except: []
  only: *main_branches

Pylint beta warnings:
  allow_failure: true
  variables:
    LINT_MODE: "beta"
  script: *pylint
  except: *main_branches

Flake8:
  script:
    - flake8

# Automated tests
Install and test addons:
  variables:
    ADDON_CATEGORIES: "--private --extra"
  script:
    - coverage
  coverage: /TOTAL.* (\d+)%/

# Runbot
Boot runbot:
  stage: deploy
  variables:
    DOMAIN_TEST: $CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
  environment:
    name: review $CI_COMMIT_REF_NAME
    # TODO Reuse $DOMAIN_TEST instead
    # HACK https://gitlab.com/gitlab-org/gitlab-runner/issues/2487
    url: http://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN:$REVIEW_PORT
    on_stop: Destroy runbot
  script:
    - docker-compose up -d

Destroy runbot:
  stage: deploy
  when: manual
  environment:
    name: review $CI_COMMIT_REF_NAME
    action: stop
  script:
    - destroy
