variables:
  COMPOSE_FILE: test.yaml
  COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG-$CI_PIPELINE_ID
  QA_VOLUME: qa-$CI_PIPELINE_ID
  REVIEW_DOMAIN: ci.gitlab.tecnativa.com
  REVIEW_PORT: 81

stages:
  - build
  - install
  - test
  - test_cleanup
  - deploy

# Build
Pull and build images:
  stage: build
  script:
    - build

# Install
Install addons:
  stage: install
  variables:
    ADDON_CATEGORIES: "--private --extra"
  script:
    - addons-install

# Lint
Pylint loose: &pylint
  variables:
    LINT_MODE: "loose"
  script:
    - pylint

Pylint strict:
  <<: *pylint
  variables:
    LINT_MODE: "strict"
  except: &main_branches
    - ^\d+\.\d+$

Pylint strict warnings:
  <<: *pylint
  allow_failure: true
  variables:
    LINT_MODE: "strict"
  only: *main_branches

Pylint beta warnings:
  <<: *pylint
  allow_failure: true
  variables:
    LINT_MODE: "beta"

Flake8:
  script:
    - flake8

# Automated tests
Test addons:
  variables:
    ADDON_CATEGORIES: >
      --extra
      --private
      --without base_bank_from_iban
      --without base_location
      --without base_location_geonames_import
      --without currency_rate_update
      --without l10n_es
      --without l10n_es_partner
      --without l10n_es_toponyms
  script:
    - coverage
    - mv artifacts/coverage .
  artifacts:
    paths:
      - coverage
    when: always
  coverage: /TOTAL.* (\d+)%/

# Free resources if something failed
Cleanup failed test resources:
  stage: test_cleanup
  when: on_failure
  script:
    - shutdown

# Runbot
Boot runbot:
  stage: deploy
  variables:
    DOMAIN_TEST: $CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN
  environment:
    name: review $CI_COMMIT_REF_NAME
    # TODO Reuse $DOMAIN_TEST instead
    # HACK https://gitlab.com/gitlab-org/gitlab-runner/issues/2487
    url: http://$CI_ENVIRONMENT_SLUG.$REVIEW_DOMAIN:$REVIEW_PORT
    on_stop: Destroy runbot
  script:
    - docker-compose up -d

Destroy runbot:
  stage: deploy
  when: manual
  environment:
    name: review $CI_COMMIT_REF_NAME
    action: stop
  script:
    - destroy
